"""Added health_status to Livestock

Revision ID: 19ec464fc2a0
Revises: 
Create Date: 2025-05-22 22:43:49.495108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19ec464fc2a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.alter_column('species',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('health_status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.alter_column('health_status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('breed',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
